# Generated by Django 4.2.18 on 2025-03-13 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parameter",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, unique=True)),
                ("monitored", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.IntegerField(unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("registered", models.BooleanField(default=False)),
                (
                    "instruments",
                    models.ManyToManyField(related_name="_usernotification_instruments+", to="report.instrument"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatusVariable",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(max_length=128)),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="timestamp")),
                (
                    "instrument_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="report.instrument"),
                ),
                ("key_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="dasmon.parameter")),
            ],
        ),
        migrations.CreateModel(
            name="StatusCache",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=128)),
                ("timestamp", models.DateTimeField(auto_now=True, verbose_name="timestamp")),
                (
                    "instrument_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="report.instrument"),
                ),
                ("key_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="dasmon.parameter")),
            ],
        ),
        migrations.CreateModel(
            name="Signal",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("source", models.CharField(max_length=40)),
                ("message", models.CharField(max_length=250)),
                ("level", models.IntegerField()),
                ("timestamp", models.DateTimeField(verbose_name="timestamp")),
                (
                    "instrument_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="report.instrument"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyURL",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.CharField(max_length=128)),
                ("long_name", models.CharField(max_length=40)),
                (
                    "instrument_id",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="report.instrument"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActiveInstrument",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_alive", models.BooleanField(default=True)),
                ("is_adara", models.BooleanField(default=True)),
                ("has_pvsd", models.BooleanField(default=False)),
                ("has_pvstreamer", models.BooleanField(default=True)),
                (
                    "instrument_id",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="report.instrument"),
                ),
            ],
        ),
    ]
