# Generated by Django 4.2.20 on 2025-03-13 23:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dasmon", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LegacyURL",
        ),
    ]
