# File introduces automated checks triggered on git events
# to enable run `pip install pre-commit && pre-commit install`

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-json
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements
        exclude: '\.template$|tests/data/'
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: sort-simple-yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: '\.template$|tests/data/'
      - id: ruff-format
        exclude: '\.template$|tests/data/'
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.33.0
    hooks:
      - id: eslint
        args: [--fix, --exit-on-fatal-error, --no-config-lookup]
        exclude: 'src/webmon_app/reporting/static/thirdparty/'
