channels:
- conda-forge
dependencies:
- build
- flake8
- pytest<7
- pytest-django
- pytest-cov
- python-dotenv
- sphinx
- lxml
- pip
- pip:
  - bump2version
  - check-wheel-contents
  - pytest-pythonpath
