name: webmon
channels:
  - conda-forge
  - oncat
dependencies:
  - python=3.11
  - django=4.2
  - gunicorn
  - make
  - oauthlib
  - psycopg2-binary=2.9.3
  - psutil
  - python-ldap>=3.1
  - requests-oauthlib
  - setuptools
  - stomp.py=8
  - urllib3
  - versioningit
  - pyoncat
  - sphinx_rtd_theme=1.2.*
  - sphinxcontrib-mermaid
  - django-health-check
  - beautifulsoup4
  - pip
  - python-dotenv
  - lxml
  - pip:
    - django-auth-ldap==5.1.0
  - pytest
  - pytest-django
  - click!=8.2.2
