name: webmon
channels:
  - conda-forge
  - oncat
dependencies:
  - python=3.10
  - django=4.2
  - gunicorn
  - httplib2
  - make
  - oauthlib
  - postgresql
  - psycopg>=3.1.8
  - psutil
  - python-ldap>=3.1
  - requests-oauthlib
  - setuptools
  - stomp.py=8
  - urllib3
  - versioningit~=1.1
  - pyoncat
  - sphinx_rtd_theme=1.2.*  # readthedocs use this env file, and we need to install this theme here
  - sphinxcontrib-mermaid
  - django-health-check
  - pip
  - pip:
    - django-auth-ldap==4.1.0
