name: webmon
channels:
  - conda-forge
  - oncat
dependencies:
  - python=3.10
  - django<3.2
  - gunicorn
  - httplib2
  - make
  - oauthlib
  - postgresql=14
  - psycopg2-binary=2.9.3
  - psutil
  - python-ldap>=3.1
  - requests-oauthlib
  - setuptools
  - stomp.py=8
  - urllib3
  - versioningit~=1.1
  - pyoncat
  - sphinx_rtd_theme=1.2.*  # readthedocs use this env file, and we need to install this theme here
  - pip
  - pip:
    - django-auth-ldap==4.1.0
    - django-health-check
