channels:
  - conda-forge
dependencies:
  - flake8
  - python-dotenv
  - python-build
  - pytest
  - pytest-django
  - pytest-cov
  - pre-commit
  - sphinx
  - sphinx_rtd_theme=1.2.*
  - lxml
  - wheel
  - check-wheel-contents
