name: webmon
channels:
  - conda-forge
  - oncat
dependencies:
  - python=3.11
  - django=4.2
  - gunicorn
  - make
  - oauthlib
  - psycopg2-binary=2.9.3
  - psutil
  - python-ldap>=3.1
  - requests-oauthlib
  - setuptools
  - stomp.py=8
  - urllib3
  - versioningit
  - pyoncat
  - sphinx_rtd_theme=1.2.*  # readthedocs use this env file, and we need to install this theme here
  - sphinxcontrib-mermaid
  - django-health-check
  - pip
  - pip:
    - django-auth-ldap==5.1.0
