channels:
- conda-forge
dependencies:
- build
- flake8
- pytest<7
- pytest-django
- pytest-cov
- python-dotenv
- python-build
- pre-commit
- sphinx
- sphinx_rtd_theme=1.2.*
- lxml
- pip
- pip:
  - check-wheel-contents
  - pytest-pythonpath
