name: webmon
channels:
- conda-forge
dependencies:
- python=3.7
- django=3.2
- gunicorn
- httplib2
- make
- oauthlib
- postgresql=14
- psycopg2-binary=2.9.3
- python-ldap>=3.1
- requests-oauthlib
- setuptools
- stomp.py=7.0.0
- urllib3
- pip
- pip:
  - django-auth-ldap==4.0.0
  - https://oncat.ornl.gov/packages/pyoncat-1.4.1-py3-none-any.whl
