channels:
  - conda-forge
dependencies:
  - build
  - flake8
  - python-dotenv
  - python-build
  - pre-commit
  - sphinx
  - sphinx_rtd_theme=1.2.*
  - lxml
  - pip
  - pip:
    - pytest
    - pytest-django
    - pytest-cov
    - check-wheel-contents
    - pytest-pythonpath
