channels:
  - conda-forge
dependencies:
  - flake8
  - python-dotenv
  - python-build
  - pytest<7
  - pytest-django<4.6
  - pytest-cov
  - pre-commit
  - sphinx
  - sphinx_rtd_theme=1.2.*
  - lxml
  - wheel
  - pip
  - pip:
    - check-wheel-contents
    - pytest-pythonpath
