FROM centos:7.6.1810

RUN yum install -y epel-release; \
    yum groupinstall -y 'development tools'; \
    yum install -y python-pip python-devel \
    postgresql-devel postgresql-contrib; \
    pip install django==1.6.5 stomp.py==4.1.22 psycopg2==2.5.3; \
    yum clean all; rm -rf /var/cache/yum

WORKDIR /usr/src/data_workflow
COPY ./src/. .
COPY README.md .

RUN make clean; \
    make dasmonlistener

WORKDIR /var/log
