FROM centos:7.6.1810

RUN yum install yum -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm; \
    yum install -y epel-release; \
    yum groupinstall -y 'development tools'; \
    yum install -y openldap-devel python-pip \
    python-devel postgresql96 postgresql96-devel python-psycopg2 \
    python2-oauthlib python2-requests-oauthlib \
    python2-requests; \
    yum clean all; rm -rf /var/cache/yum

WORKDIR /usr/src/data_workflow

COPY ./src/. .
COPY ./README.md .

RUN pip install --no-cache-dir -r requirements.txt;
