# Miniconda with native Python 3.10
FROM continuumio/miniconda3:23.3.1-0
RUN conda install --yes -n base conda-libmamba-solver

# Install webmonchow
RUN conda install --yes --solver=libmamba -n base -c conda-forge -c neutrons/label/rc postgresql=14 webmonchow=1.0.2rc1

# Install webmonchow from a feature branch (only to test the latest changes in webmonchow)
# RUN conda install --yes --solver=libmamba -n base -c conda-forge postgresql=14
# RUN python -m pip install git+https://github.com/neutrons/webmonchow.git@next#egg=webmonchow

# Start the AMQ and PV generators when starting the container
CMD ["sh", "-c", "broadcast_pv & broadcast_amq --broker \"activemq:61613\" & wait"]
