FROM continuumio/miniconda3

COPY conda_environment.yml .
RUN conda env update --name base --file conda_environment.yml

WORKDIR /usr/src/webmon

# copy the necessary wheels and the Makefile which knows the dependency order
COPY ./src/webmon_app/dist/django_nscd_webmon-*-none-any.whl .
COPY ./src/workflow_app/dist/django_nscd_workflow-*-none-any.whl .
COPY ./Makefile .

# move the entry-point into the volume
COPY ./src/webmon_app/docker-entrypoint.sh /usr/bin/docker-entrypoint.sh

# RUN useradd -ms /bin/bash user
# # allow in sudoers to install packages
# RUN adduser user sudo
# RUN echo "user:user" | chpasswd

# USER user

RUN chmod +x /usr/bin/docker-entrypoint.sh
ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]
