FROM continuumio/miniconda3

COPY conda_environment.yml .
RUN conda env update --name base --file conda_environment.yml

WORKDIR /usr/src/data_workflow
COPY ./src/. .
COPY README.md .

# Only do this for testing, comment out for production
RUN echo 'brokers = [("activemq", 61613)]' > dasmon_listener/local_settings.py
RUN echo 'queues=["/topic/SNS.COMMON.STATUS.WORKFLOW.0","/topic/SNS.COMMON.STATUS.AUTOREDUCE.0","/topic/SNS.*.APP.DASMON","/topic/SNS.*.STATUS.DASMON","/topic/SNS.*.SIGNAL.DASMON","/topic/SNS.*.APP.SMS","/topic/SNS.*.STATUS.SMS","/topic/SNS.*.STATUS.POSTPROCESS","/topic/SNS.COMMON.STATUS.ACK","/topic/SNS.*.STATUS.PVSD","/topic/HFIR.*.APP.DASMON","/topic/HFIR.*.STATUS.DASMON","/topic/HFIR.*.SIGNAL.DASMON","/topic/HFIR.*.APP.SMS","/topic/HFIR.*.STATUS.SMS","/topic/HFIR.*.STATUS.POSTPROCESS","/topic/HFIR.COMMON.STATUS.ACK","/topic/HFIR.*.STATUS.PVSD"]' >> dasmon_listener/local_settings.py
RUN echo 'brokers = [("activemq", 61613)]' > workflow/database/local_settings.py
