version: '3'
services:

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - web-static:/var/www/workflow/static
      - ./nginx/django.conf:/etc/nginx/conf.d/django.conf
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.d/docker-entrypoint.sh

  web: 
    restart: always
    build: .
    expose:
      - "8000"
    ports: 
      - "8000:8000"
    volumes:
      - web-django:/var/www/workflow/app
      - web-static:/var/www/workflow/static/
      - ./src/docker-entrypoint.sh:/usr/bin/docker-entrypoint.sh
    env_file:
      - .env
    command: /usr/bin/docker-entrypoint.sh
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data/
        
volumes:
  web-django:
  web-static:
  db-data:
