services:

  nginx:
    image: nginx:1.21.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-static:/var/www/workflow/static
      - web-static-livedata:/var/www/livedata/static
      - ./nginx/django.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.crt:/etc/nginx/nginx.crt
      - ./nginx/nginx.key:/etc/nginx/nginx.key
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
    depends_on:
      webmon:
        condition: service_healthy
    networks:
      default:
        ipv4_address: 172.16.238.222

  webmon:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.webmon
    volumes:
      - web-static:/var/www/workflow/static/
      - ./nginx/nginx.crt:/nginx.crt
    env_file:
      - .env
      - .env.ci
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - LOAD_INITIAL_DATA=${LOAD_INITIAL_DATA-true}
      - LDAP_SERVER_URI=${LDAP_SERVER_URI}
      - LDAP_DOMAIN_COMPONENT=${LDAP_DOMAIN_COMPONENT}
      - CATALOG_URL=${CATALOG_URL}
      - CATALOG_ID=${CATALOG_ID}
      - CATALOG_SECRET=${CATALOG_SECRET}
      - GUNICORN_CMD_ARGS=--reload --workers=8
      - REQUESTS_CA_BUNDLE=/nginx.crt
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000/ht || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    depends_on:
      db:
        condition: service_healthy

  dasmon:
    build:
      context: .
      dockerfile: Dockerfile.dasmon
    env_file:
      - .env
    command: /usr/bin/docker-entrypoint.sh
    healthcheck:
      test: ["CMD", "dasmon_listener", "status"]
    depends_on:
      activemq:
        condition: service_healthy
      webmon:
        condition: service_healthy

  workflow:
    build:
      context: .
      dockerfile: Dockerfile.workflow
    env_file:
      - .env
    command: /usr/bin/docker-entrypoint.sh
    healthcheck:
      test: ["CMD", "workflowmgr", "status"]
    depends_on:
      activemq:
        condition: service_healthy
      webmon:
        condition: service_healthy

  db:
    restart: always
    image: postgres:14
    env_file:
      - .env
    environment:
      # variables DATABASE_* should be initialized in .env file
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      # DATABASE_PORT should be initialized in .env file
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  activemq:
    image: apache/activemq-classic
    hostname: activemq
    volumes:
      - ./src/workflow_app/workflow/icat_activemq.xml:/opt/apache-activemq/conf/activemq.xml
    healthcheck:
      test: "curl --silent --show-error -u admin:admin -H 'Origin:http://localhost' 'http://localhost:8161/api/jolokia/read/org.apache.activemq:type=Broker,brokerName=localhost,service=Health' | grep --silent -e 'Good' -e 'Getting Worried'"
      interval: 5s
      timeout: 5s
      retries: 5

  autoreducer:
    build:
      context: .
      dockerfile: Dockerfile.autoreducer
    hostname: autoreducer
    healthcheck:
      test: ["CMD", "pgrep", "python"]
    depends_on:
      activemq:
        condition: service_healthy

  autoreducer_himem:
    build:
      context: .
      dockerfile: Dockerfile.autoreducer.himem
    hostname: autoreducer.himem
    healthcheck:
      test: ["CMD", "pgrep", "python"]
    depends_on:
      activemq:
        condition: service_healthy

  amq_test_gen:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.amq_test_gen
    depends_on:
      activemq:
        condition: service_healthy

  amq_pv_gen:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.pv_test_gen
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      webmon:
        condition: service_healthy

  livedata:
    restart: always
    image: ghcr.io/neutrons/live_data_server/live_data_server:latest-dev
    env_file:
      - .env
    environment:
      DJANGO_SUPERUSER_USERNAME: ${DATABASE_USER}
      DJANGO_SUPERUSER_PASSWORD: ${DATABASE_PASS}
    volumes:
      - web-static-livedata:/var/www/livedata/static
      - ./config/livedata_local_settings.py:/var/www/livedata/app/local_settings.py
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000/admin || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    depends_on:
      db:
        condition: service_healthy
      webmon:
        condition: service_healthy

  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  web-static:
  web-static-livedata:
  pgdata:


networks:
  default:
    ipam:
      config:
        - subnet: 172.16.238.0/24
