FROM ghcr.io/prefix-dev/pixi:0.53.0-bookworm-slim

# Install webmonchow
RUN pixi init --channel conda-forge --channel neutrons
RUN pixi add webmonchow=1.0.2

# Start the AMQ and PV generators when starting the container
CMD ["sh", "-c", "pixi run broadcast_pv & pixi run broadcast_amq --broker \"activemq:61613\" & wait"]
