FROM code.ornl.gov:4567/rse/images/miniconda3:4.10.3p1
RUN python -m pip install web-monitor-amq-message-generator==0.2.1 -i https://code.ornl.gov/api/v4/projects/10770/packages/pypi/simple
CMD ["webmonitor_amq_tester", "--broker", "activemq:61613"]
