version: '3'
services:

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - web-static:/var/www/workflow/static
      - ./nginx/django.conf:/etc/nginx/conf.d/django.conf
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.d/docker-entrypoint.sh
    depends_on:
      - webmon

  webmon:
    build:
      context: .
      dockerfile: Dockerfile.webmon
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - web-static:/var/www/workflow/static/
    env_file:
      - .env
    depends_on:
      - db

  dasmon:
    build:
      context: .
      dockerfile: Dockerfile.dasmon
    volumes:
      - ./src/dasmon_listener/docker-entrypoint.sh:/usr/bin/docker-entrypoint.sh
    env_file:
      - .env
    command: /usr/bin/docker-entrypoint.sh
    depends_on:
      - webmon

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data/

  activemq:
    ports:
      - "61613:61613"
      - "8161:8161"
    image: rmohr/activemq
    volumes:
      - ./src/workflow/icat_activemq.xml:/opt/activemq/conf/activemq.xml

volumes:
  web-django:
  web-static:
  db-data:
