version: '3'
services:

  nginx:
    image: code.ornl.gov:4567/rse/images/nginx:1.21.1
    ports:
      - "80:80"
    volumes:
      - web-static:/var/www/workflow/static
      - ./nginx/django.conf:/etc/nginx/conf.d/django.conf
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.d/docker-entrypoint.sh

  webmon: 
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.webmon
    expose:
      - "8000"
    ports: 
      - "8000:8000"
    volumes:
      - web-static:/var/www/workflow/static/
      - ./src/reporting/docker-entrypoint.sh:/usr/bin/docker-entrypoint.sh
    env_file:
      - .env
    command: /usr/bin/docker-entrypoint.sh
    depends_on:
      - db

  dasmon: 
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.dasmon
    volumes:
      - ./src/dasmon_listener/docker-entrypoint.sh:/usr/bin/docker-entrypoint.sh
    env_file:
      - .env
    command: /usr/bin/docker-entrypoint.sh
    depends_on:
      - webmon
  
  db:
    restart: always
    image: postgres:14
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data/

  activemq:
    restart: always
    image: rmohr/activemq
    volumes:
      - ./src/workflow/icat_activemq.xml:/opt/activemq/conf/activemq.xml

volumes:
  web-django:
  web-static:
  db-data:
