FROM continuumio/miniconda3:4.12.0

# Install conda-libmamba-solver
RUN conda update -n base -c defaults conda
RUN conda install --yes -n base conda-libmamba-solver

# Install Python 3.10 and PostgreSQL using libmamba solver
RUN conda install --yes --solver=libmamba -c conda-forge python=3.10 postgresql=14

# Install webmonchow
RUN python -m pip install git+https://github.com/neutrons/webmonchow.git@next#egg=webmonchow

# Start the AMQ and PV generators when starting the container
CMD ["sh", "-c", "broadcast_pv & broadcast_amq --broker \"activemq:61613\" & wait"]
