name: webmon
channels:
- conda-forge
dependencies:
- make
- python=3.7
- django=1.11.25
- stomp.py=4.1.23
- setuptools
- psycopg2-binary>=2.8
- postgresql
- oauthlib
- requests-oauthlib
- requests
- amqp
- billiard
- certifi
- chardet
- decorator
- contextlib2
- docopt
- gunicorn
- idna
- ipython_genutils
- jsonschema
- jupyter_core
- kitchen
- kombu
- nbformat
- plotly
- pyasn1
- pyasn1-modules
- pycurl
- gpgme
- pytz
- xattr
- retrying
- six
- traitlets
- urllib3
- vine
- httplib2
- gunicorn
- python-ldap
- pip
- gcc
- pip:
  - django-auth-ldap==1.6.0
  - https://oncat.ornl.gov/packages/pyoncat-1.4.1-py3-none-any.whl
