name: webmon
channels:
- conda-forge
dependencies:
- make
- python=3.7
- django=1.11.25
- stomp.py=7.0.0
- psycopg2=2.8.6
- setuptools
- postgresql
- oauthlib
- requests-oauthlib
- gunicorn
- urllib3
- httplib2
- gunicorn
- python-ldap
- pip
- pip:
  - django-auth-ldap==1.6.0
  - https://oncat.ornl.gov/packages/pyoncat-1.4.1-py3-none-any.whl
