# Generated by Django 4.2.18 on 2025-03-13 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataRun",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_number", models.IntegerField()),
                ("file", models.CharField(max_length=128)),
                ("created_on", models.DateTimeField(auto_now_add=True, verbose_name="Timestamp")),
            ],
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="StatusQueue",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_workflow_input", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowSummary",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("complete", models.BooleanField(default=False)),
                ("catalog_started", models.BooleanField(default=False)),
                ("cataloged", models.BooleanField(default=False)),
                ("reduction_needed", models.BooleanField(default=True)),
                ("reduction_started", models.BooleanField(default=False)),
                ("reduced", models.BooleanField(default=False)),
                ("reduction_cataloged", models.BooleanField(default=False)),
                ("reduction_catalog_started", models.BooleanField(default=False)),
                ("run_id", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="report.datarun")),
            ],
            options={
                "verbose_name_plural": "Workflow summaries",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_class", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "input_queue_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="report.statusqueue"),
                ),
                (
                    "instrument_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="report.instrument"),
                ),
                (
                    "success_queue_ids",
                    models.ManyToManyField(
                        blank=True, related_name="_task_success_queue_ids+", to="report.statusqueue"
                    ),
                ),
                (
                    "task_queue_ids",
                    models.ManyToManyField(blank=True, related_name="_task_task_queue_ids+", to="report.statusqueue"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatusQueueMessageCount",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message_count", models.IntegerField()),
                ("created_on", models.DateTimeField(auto_now_add=True, verbose_name="Timestamp")),
                ("queue", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="report.statusqueue")),
            ],
        ),
        migrations.CreateModel(
            name="RunStatus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message_id", models.CharField(max_length=100, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, verbose_name="Timestamp")),
                ("queue_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="report.statusqueue")),
                ("run_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="report.datarun")),
            ],
            options={
                "verbose_name_plural": "Run status",
            },
        ),
        migrations.CreateModel(
            name="IPTS",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("expt_name", models.CharField(max_length=20, unique=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, verbose_name="Timestamp")),
                ("instruments", models.ManyToManyField(related_name="_ipts_instruments+", to="report.instrument")),
            ],
            options={
                "verbose_name_plural": "IPTS",
            },
        ),
        migrations.CreateModel(
            name="InstrumentStatus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "instrument_id",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="report.instrument"),
                ),
                (
                    "last_run_id",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="report.datarun"),
                ),
            ],
            options={
                "verbose_name_plural": "Instrument status",
            },
        ),
        migrations.CreateModel(
            name="Information",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=200, null=True)),
                (
                    "run_status_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="report.runstatus"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Error",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=200, null=True)),
                (
                    "run_status_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="report.runstatus"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="datarun",
            name="instrument_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="report.instrument"),
        ),
        migrations.AddField(
            model_name="datarun",
            name="ipts_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="report.ipts"),
        ),
    ]
