INSERT INTO report_statusinfo VALUES(1, 'POSTPROCESS.DATA_READY');
INSERT INTO report_statusinfo VALUES(2, 'CATALOG.STARTED');
INSERT INTO report_statusinfo VALUES(3, 'CATALOG.COMPLETE');
INSERT INTO report_statusinfo VALUES(4, 'REDUCTION.STARTED');
INSERT INTO report_statusinfo VALUES(5, 'REDUCTION.COMPLETE');
INSERT INTO report_statusinfo VALUES(6, 'REDUCTION_CATALOG.STARTED');
INSERT INTO report_statusinfo VALUES(7, 'REDUCTION_CATALOG.COMPLETE');