# Generated by Django 4.2.18 on 2025-03-13 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("report", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="PVName",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("monitored", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PVStringCache",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.TextField()),
                ("status", models.IntegerField()),
                ("update_time", models.IntegerField()),
                (
                    "instrument",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="report.instrument"),
                ),
                ("name", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pvmon.pvname")),
            ],
            options={
                "verbose_name_plural": "PV string cache",
            },
        ),
        migrations.CreateModel(
            name="PVString",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.TextField()),
                ("status", models.IntegerField()),
                ("update_time", models.IntegerField()),
                (
                    "instrument",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="report.instrument"),
                ),
                ("name", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pvmon.pvname")),
            ],
            options={
                "verbose_name_plural": "PV strings",
            },
        ),
        migrations.CreateModel(
            name="PVCache",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.FloatField()),
                ("status", models.IntegerField()),
                ("update_time", models.IntegerField()),
                (
                    "instrument",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="report.instrument"),
                ),
                ("name", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pvmon.pvname")),
            ],
            options={
                "verbose_name_plural": "PV cache",
            },
        ),
        migrations.CreateModel(
            name="PV",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value", models.FloatField()),
                ("status", models.IntegerField()),
                ("update_time", models.IntegerField()),
                (
                    "instrument",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="report.instrument"),
                ),
                ("name", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pvmon.pvname")),
            ],
            options={
                "verbose_name_plural": "PVs",
            },
        ),
        migrations.CreateModel(
            name="MonitoredVariable",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rule_name", models.CharField(blank=True, default="", max_length=50)),
                ("instrument", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="report.instrument")),
                (
                    "pv_name",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="pvmon.pvname"
                    ),
                ),
            ],
        ),
    ]
