# Generated by Django 4.2.23 on 2025-06-26 05:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pvmon", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PVString",
        ),
    ]
