# Generated by Django 4.2.23 on 2025-08-29 05:08

import datetime
from functools import partial

from django.db import migrations, models
from django.utils import timezone


def convert_epoch_to_datetime(apps, schema_editor, model_name):
    model = apps.get_model("pvmon", model_name)
    tz = timezone.get_current_timezone()
    for obj in model.objects.all():
        obj.timestamp = datetime.datetime.fromtimestamp(obj.update_time, tz)
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("pvmon", "0002_delete_pvstring"),
    ]

    operations = [
        migrations.AddField(
            model_name="pv",
            name="timestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(partial(convert_epoch_to_datetime, model_name="PV")),
        migrations.RemoveField(
            model_name="pv",
            name="update_time",
        ),
        migrations.AddField(
            model_name="pvcache",
            name="timestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(partial(convert_epoch_to_datetime, model_name="PVCache")),
        migrations.RemoveField(
            model_name="pvcache",
            name="update_time",
        ),
        migrations.AddField(
            model_name="pvstringcache",
            name="timestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(partial(convert_epoch_to_datetime, model_name="PVStringCache")),
        migrations.RemoveField(
            model_name="pvstringcache",
            name="update_time",
        ),
    ]
