# Generated by Django 4.2.23 on 2025-09-10 12:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pvmon", "0002_delete_pvstring"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoredvariable",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monitoredvariable",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
