# Generated by Django 4.2.18 on 2025-03-13 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("report", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReductionProperty",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.TextField()),
                ("value", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now=True, verbose_name="timestamp")),
                ("instrument", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="report.instrument")),
            ],
            options={
                "verbose_name_plural": "Reduction properties",
            },
        ),
        migrations.CreateModel(
            name="PropertyModification",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now=True, verbose_name="timestamp")),
                (
                    "property",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reduction.reductionproperty"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyDefault",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now=True, verbose_name="timestamp")),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="reduction.reductionproperty"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField()),
                ("value", models.TextField()),
                ("instrument", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="report.instrument")),
                (
                    "property",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reduction.reductionproperty"),
                ),
            ],
        ),
    ]
