#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username postgres --dbname postgres <<-EOSQL
    CREATE USER $DATABASE_USER WITH ENCRYPTED PASSWORD '$DATABASE_PASS';
    CREATE DATABASE $DATABASE_NAME OWNER $DATABASE_USER;
    GRANT ALL PRIVILEGES ON DATABASE $DATABASE_NAME TO $DATABASE_USER;
    CREATE USER $AMQDB_USER;
    CREATE DATABASE $AMQDB_NAME OWNER $AMQDB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $AMQDB_NAME TO $AMQDB_USER;
EOSQL
