# Generated by Django 4.2.18 on 2025-03-13 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reporting.users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeveloperNode",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="SiteNotification",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("view", reporting.users.models.TruncatingCharField(max_length=64)),
                ("path", reporting.users.models.TruncatingCharField(max_length=128)),
                ("ip", models.CharField(max_length=64)),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="timestamp")),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
