name: Trigger ORNL Development Pipeline
on: 
  push:
    branches:
      - dev
jobs:
  ornl-trigger-dev:
    runs-on: ubuntu-20.04
    steps:
      - run: curl -sX POST -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} -F ref=dev ${{ secrets.GITLAB_TRIGGER_URL }} > /dev/null
