name: Trigger ORNL GitLab Pipeline
on: [push]
jobs:
  trigger-ci-job:
    runs-on: self-hosted
    steps:
      - run: curl -X POST -F token=$TOKEN -F ref=$REF $URL 
        env:
          TOKEN: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
          REF: ${{ secrets.GITLAB_TRIGGER_REF }}
          URL: ${{ secrets.GITLAB_TRIGGER_URL }}