name: Systemtests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
    - name: Setup libmamba solver
      run: |
        conda install -n base conda-libmamba-solver
        conda config --set solver libmamba
    - name: Install requirements
      run: |
        # --quiet should turn off progress bars to make logs more readable
        conda env create --file conda_environment.yml --quiet
        conda activate webmon
        conda env update --file conda_development.yml --quiet
    - name: Build requirements
      run: |
        conda activate webmon
        make all
    - name: Install packages
      run: |
        conda activate webmon
        pip install src/dasmon_app/dist/django_nscd_dasmon-*.whl src/webmon_app/dist/django_nscd_webmon-*.whl src/workflow_app/dist/django_nscd_workflow-*.whl
    - name: Stand up docker containers
      run: docker compose up --build -d
      env:
          DJANGO_SETTINGS_MODULE: reporting.reporting_app.settings.envtest
          LDAP_SERVER_URI: .
          LDAP_DOMAIN_COMPONENT: .
    - name: Wait for everything to start up
      run: sleep 66
    - name: Run system tests
      run: |
        docker-compose exec webmon bash -c "conda activate webmon && pytest tests/"
    - name: stop containers
      if: ${{ always() }}
      run: |
        docker compose down
