name: Systemtests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup pixi
      uses: prefix-dev/setup-pixi@v0.9.0
      with:
        environments: test
    - name: Build requirements
      run:  make all
    - name: Stand up docker containers
      run: docker compose up --build --wait --wait-timeout 300
      env:
          DJANGO_SETTINGS_MODULE: reporting.reporting_app.settings.envtest
          LDAP_SERVER_URI: .
          LDAP_DOMAIN_COMPONENT: .
    - name: Wait for everything to start up
      run: sleep 66
    - name: Test with pytest
      run: pixi run systemtests
    - name: Stand down docker containers
      run: docker compose down
