name: Systemtests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
    - name: Setup libmamba solver
      run: |
        conda install -n base conda-libmamba-solver
        conda config --set solver libmamba
    - name: Install requirements
      run: |
        # --quiet should turn off progress bars to make logs more readable
        conda env create --file conda_environment.yml --quiet
        conda activate webmon
        conda env update --file conda_development.yml --quiet
    - name: Build requirements
      run: |
        conda activate webmon
        make all
    - name: Install packages
      run: |
        conda activate webmon
        pip install src/dasmon_app/dist/django_nscd_dasmon-*.whl src/webmon_app/dist/django_nscd_webmon-*.whl src/workflow_app/dist/django_nscd_workflow-*.whl
    - name: Stand up docker containers
      run: docker compose up --build -d
      env:
          DJANGO_SETTINGS_MODULE: reporting.reporting_app.settings.envtest
          LDAP_SERVER_URI: .
          LDAP_DOMAIN_COMPONENT: .
    - name: Wait for everything to start up
      run: sleep 66
    - name: Test with pytest
      run: |
        conda activate webmon
        python -m pytest tests -k "not (test_plotly_v5_plot_publishing_and_display or test_plotly_v6_plot_publishing_and_display or test_plot_without_version_metadata_uses_default or test_autoreducer_v5_generates_correct_metadata or test_autoreducer_himem_v6_generates_correct_metadata or TestLiveData or TestPlotlyVersions or test_reduction_request_livedata)"
      env:
          DJANGO_SETTINGS_MODULE: reporting.reporting_app.settings.envtest
          LDAP_SERVER_URI: .
          LDAP_DOMAIN_COMPONENT: .
          LIVE_PLOT_SECRET_KEY: secretKey
    - name: Stand down docker containers
      run: docker compose down
